apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-assistant-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-assistant
  template:
    metadata:
      labels:
        app: ai-assistant
    spec:
      containers:
        - name: ai-assistant
          image: ai-assistant:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: api_key
            - name: WEBHOOK_SECRET
              value: seu_token_seguro
